import { useEffect,useMemo,useState } from "react";
import { Link,useNavigate,useParams,useSearchParams } from "react-router-dom";
import { BookOpen,ChevronRight,HandHeart,Loader2,Share2,Sparkles } from "lucide-react";
import { BibliaLayout } from "./BibliaLayout";
import { getBibliaCapitulo,getBibliaCatalogo,getBibliaVersiones,type BibliaLibro,type BibliaVersion,type BibliaVersiculo } from "@/services/bibliaService";
import { createBibleStudy,getBibleStudy,getStudyStatus,type BibleStudy } from "@/services/bibleStudyService";
import { equivalentChapterFromPlatense } from "@/utils/bibliaVersification";
import { supabase } from "@/integrations/supabase/client";

const tabs=["Texto","Comparación","Estructura","Teología","Oración"] as const;
type Tab=typeof tabs[number];
type SelectionMode="chapter"|"range";
type TextEntry={disponible:boolean;texto:string}; type Comparison={epoca:string;estilo:string;matices:string[]};
type Data={titulo?:string;textos?:Record<string,TextEntry>;comprension_global?:string;comparacion_traducciones?:Record<string,Comparison|string|string[]>;delimitacion?:{unidad:string;justificacion:string};genero_literario?:{tipo:string;explicacion:string};estructura?:Array<{versiculos:string;titulo:string;explicacion:string}>;proposiciones?:Array<{texto:string;tipo:string;explicacion:string}>;palabras_clave?:Array<{termino:string;significado:string;funcion_en_el_texto:string}>;contexto_historico?:string;contexto_biblico?:string;mensaje_teologico?:string;mensaje_cristologico?:string;referencias_cruzadas?:Array<{referencia:string;relacion:string}>;actualizacion_pastoral?:string;aplicacion_espiritual?:string;preguntas_para_meditar?:string[];lectio_divina?:Record<string,string>};
type PreviewColumn={version:BibliaVersion;capitulo:number;versiculos:BibliaVersiculo[]};
export default function BibliaEstudio(){const {id}=useParams();const nav=useNavigate();const [params]=useSearchParams();const initialBook=(params.get("libro")||"PSA").toUpperCase();const initialChapter=Math.max(1,Number(params.get("cap")||23));const [study,setStudy]=useState<BibleStudy|null>(null);const [books,setBooks]=useState<BibliaLibro[]>([]);const [book,setBook]=useState(initialBook);const [chapter,setChapter]=useState(initialChapter);const [selectionMode,setSelectionMode]=useState<SelectionMode>("range");const [rangeAnchor,setRangeAnchor]=useState<number|null>(null);const [start,setStart]=useState(1);const [end,setEnd]=useState(5);const [preview,setPreview]=useState<PreviewColumn[]>([]);const [previewLoading,setPreviewLoading]=useState(true);const [comparisonRequested,setComparisonRequested]=useState(Boolean(id));const [tab,setTab]=useState<Tab>("Texto");const [loading,setLoading]=useState(Boolean(id));const [configured,setConfigured]=useState<boolean|null>(null);const [ready,setReady]=useState<boolean|null>(null);const [availabilityMessage,setAvailabilityMessage]=useState("");const [error,setError]=useState("");
const [authenticated,setAuthenticated]=useState<boolean|null>(null);
useEffect(()=>{getBibliaCatalogo().then(x=>setBooks(x.libros)).catch(e=>setError(e.message));getStudyStatus().then(x=>{setConfigured(Boolean(x.configured));setReady(Boolean(x.ready));setAvailabilityMessage(x.message||"");}).catch(()=>{setConfigured(false);setReady(false);});},[]);
useEffect(()=>{let active=true;void supabase.auth.getSession().then(({data})=>{if(active)setAuthenticated(Boolean(data.session));});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{if(active)setAuthenticated(Boolean(session));});return()=>{active=false;data.subscription.unsubscribe();};},[]);
useEffect(()=>{let active=true;setPreviewLoading(true);getBibliaVersiones().then(async versions=>{const preferred=versions.filter(version=>{const value=`${version.codigo} ${version.nombre}`.toUpperCase();return value.includes("SPAPLATENSE")||value.includes("PLATENSE")||value.includes("STRAUBINGER")||value.includes("TORRES")||value.includes("SCIO")||value.includes("SCÍO");}).slice(0,3);const comparable=preferred.flatMap(version=>{const equivalentChapter=equivalentChapterFromPlatense(book,chapter,version);return equivalentChapter===null?[]:[{version,chapter:equivalentChapter}];});const results=await Promise.allSettled(comparable.map(item=>getBibliaCapitulo(book,item.chapter,item.version.codigo)));if(!active)return;setPreview(results.flatMap(result=>result.status==="fulfilled"?[{version:result.value.version,capitulo:result.value.capitulo,versiculos:result.value.versiculos}]:[]));}).catch(()=>active&&setPreview([])).finally(()=>active&&setPreviewLoading(false));return()=>{active=false;};},[book,chapter]);
useEffect(()=>{if(!id)return;setLoading(true);getBibleStudy(Number(id)).then(setStudy).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[id]);
const generate=async()=>{const firstVerse=verseOptions[0];const lastVerse=verseOptions[verseOptions.length-1];const selectedStart=selectionMode==="chapter"?firstVerse:start;const selectedEnd=selectionMode==="chapter"?lastVerse:end;if(!selectedStart||!selectedEnd){setError("Selecciona un pasaje válido.");return;}setStart(selectedStart);setEnd(selectedEnd);setComparisonRequested(true);setLoading(true);setError("");try{const result=await createBibleStudy({libro_codigo:book,capitulo_inicio:chapter,versiculo_inicio:selectedStart,capitulo_fin:chapter,versiculo_fin:selectedEnd});setStudy(result);nav(`/biblia/estudio/${result.id}`,{replace:true});}catch(e){const msg=e instanceof Error?e.message:"";if(msg==="AUTH_REQUIRED")nav(`/acceso?next=${encodeURIComponent(`/biblia/estudio?libro=${book}&cap=${chapter}`)}`);else setError(msg);}finally{setLoading(false);}};
const currentBook=books.find(item=>item.codigo===book);const chapterOptions=Array.from({length:currentBook?.capitulos||1},(_,index)=>index+1);const verseOptions=useMemo(()=>{const primaryColumn=preview.find(column=>column.version.codigo.toUpperCase().includes("SPAPLATENSE"))||preview[0];return (primaryColumn?.versiculos||[]).map(verse=>verse.versiculo);},[preview]);
const selectRangeVerse=(value:number)=>{setComparisonRequested(false);if(rangeAnchor===null){setStart(value);setEnd(value);setRangeAnchor(value);return;}setStart(Math.min(rangeAnchor,value));setEnd(Math.max(rangeAnchor,value));setRangeAnchor(null);};
const hasStudyContent=Boolean(study&&study.estado!=="error"&&Object.keys(study.contenido||{}).length>0);
useEffect(()=>{if(verseOptions.length===0)return;const first=verseOptions[0];const last=verseOptions[verseOptions.length-1];if(selectionMode==="chapter"){if(start!==first)setStart(first);if(end!==last)setEnd(last);return;}const nextStart=verseOptions.includes(start)?start:first;const nextEnd=verseOptions.includes(end)&&end>=nextStart?end:(verseOptions[Math.min(4,verseOptions.length-1)]??nextStart);if(nextStart!==start)setStart(nextStart);if(nextEnd!==end)setEnd(nextEnd);},[verseOptions,selectionMode,start,end]);
return <BibliaLayout title="Estudio Bíblico" back="/biblia">
  {!hasStudyContent&&!loading&&<section className="mb-4 rounded-[1.5rem] border border-[#D4AF37]/25 bg-[#0B0B0B] p-5">
    <div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#D4AF37]/10 text-[#D4AF37]"><Sparkles/></span><div><h1 className="font-display text-2xl">Seleccionar el pasaje</h1><p className="text-sm text-[#C9C3B3]">Estudia un capítulo completo o selecciona un rango de versículos.</p></div></div>
    {ready===false&&<p className="mt-4 rounded-xl border border-[#D4AF37]/20 bg-[#D4AF37]/10 p-3 text-sm text-[#F2D27A]">{availabilityMessage||(configured===false?"Servicio de estudio no configurado.":"El estudio con inteligencia artificial estar\u00e1 disponible cuando finalice la revisi\u00f3n de equivalencias b\u00edblicas.")}</p>}
    <div className="mt-5 grid grid-cols-2 gap-3">
      <Field label="Libro"><select value={book} onChange={e=>{setBook(e.target.value);setChapter(1);setStart(1);setEnd(5);setRangeAnchor(null);setComparisonRequested(false);}}>{books.map(b=><option key={b.codigo} value={b.codigo}>{b.nombre}</option>)}</select></Field>
      <Field label="Capítulo"><select value={chapter} onChange={e=>{setChapter(Number(e.target.value));setStart(1);setEnd(5);setRangeAnchor(null);setComparisonRequested(false);}}>{chapterOptions.map(value=><option key={value} value={value}>{value}</option>)}</select></Field>
    </div>
    <div className="mt-4 grid grid-cols-2 gap-2 rounded-xl border border-[#D4AF37]/20 bg-[#111] p-1">
      <button type="button" onClick={()=>{setSelectionMode("chapter");setRangeAnchor(null);setComparisonRequested(false);}} className={`rounded-lg px-3 py-2 text-xs font-semibold ${selectionMode==="chapter"?"bg-[#D4AF37] text-black":"text-[#C9C3B3]"}`}>Capítulo completo</button>
      <button type="button" onClick={()=>{setSelectionMode("range");setRangeAnchor(null);setComparisonRequested(false);}} className={`rounded-lg px-3 py-2 text-xs font-semibold ${selectionMode==="range"?"bg-[#D4AF37] text-black":"text-[#C9C3B3]"}`}>Rango de versículos</button>
    </div>
    {previewLoading?<div className="flex justify-center py-4"><Loader2 className="h-5 w-5 animate-spin text-[#D4AF37]"/></div>:<VerseGrid values={verseOptions} start={start} end={end} mode={selectionMode} awaitingEnd={rangeAnchor!==null} onSelect={selectRangeVerse}/>} 
    {authenticated===true?<button disabled={ready!==true||previewLoading||preview.length===0} onClick={generate} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#D4AF37] to-[#F2D27A] py-3 font-bold text-black shadow-[0_14px_32px_rgba(212,175,55,0.2)] disabled:cursor-not-allowed disabled:opacity-40">Profundizar el pasaje<ChevronRight className="h-4 w-4"/></button>:<button disabled={authenticated===null||previewLoading||preview.length===0} onClick={()=>setComparisonRequested(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-[#D4AF37]/45 bg-[#D4AF37]/10 py-3 font-bold text-[#F2D27A] disabled:opacity-40">Comparar versiones<ChevronRight className="h-4 w-4"/></button>}
  </section>}
  {comparisonRequested&&preview.length>0&&<ComparisonPreview columns={preview} start={start} end={end}/>} 
  {comparisonRequested&&authenticated===false&&<GuestStudyPrompt next={`/biblia/estudio?libro=${book}&cap=${chapter}`}/>}
  {loading&&<Generating/>}
  {error&&<div className="mb-4 rounded-2xl border border-red-500/30 bg-red-950/20 p-4 text-sm text-red-200"><p>{error||"No fue posible generar el estudio en este momento."}</p><button onClick={()=>id?location.reload():generate()} className="mt-3 rounded-lg border border-red-300/30 px-3 py-2">Intentar nuevamente</button></div>}
  {hasStudyContent&&study&&<><StudyView study={study} tab={tab} setTab={setTab}/><SupportCard/></>} 
</BibliaLayout>}

function VerseGrid({values,start,end,mode,awaitingEnd,onSelect}:{values:number[];start:number;end:number;mode:SelectionMode;awaitingEnd:boolean;onSelect:(value:number)=>void}){return <div className="mt-4 rounded-xl border border-[#D4AF37]/20 bg-[#111] p-3"><div className="mb-3 flex items-center justify-between gap-3 text-xs"><span className="font-semibold text-[#D4AF37]">{mode==="chapter"?"Capítulo completo":awaitingEnd?"Selecciona el último versículo":"Selecciona el primer versículo"}</span><span className="text-[#C9C3B3]">{start===end?`Versículo ${start}`:`Versículos ${start}–${end}`}</span></div><div className="grid grid-cols-6 gap-2 sm:grid-cols-8">{values.map(value=>{const selected=mode==="chapter"||(value>=start&&value<=end);const boundary=mode==="range"&&(value===start||value===end);return <button key={value} type="button" disabled={mode==="chapter"} onClick={()=>onSelect(value)} aria-pressed={selected} className={`aspect-square rounded-lg border text-sm font-semibold transition ${selected?"border-[#D4AF37] bg-[#D4AF37]/20 text-[#F2D27A]":"border-white/10 bg-black/30 text-[#C9C3B3] hover:border-[#D4AF37]/50"} ${boundary?"ring-2 ring-[#F2D27A]/70":""} disabled:cursor-default`}>{value}</button>;})}</div></div>}

function GuestStudyPrompt({next}:{next:string}){return <aside className="mb-4 rounded-[1.35rem] border border-[#D4AF37]/30 bg-[#0B0B0B] p-5 text-center"><BookOpen className="mx-auto h-7 w-7 text-[#D4AF37]"/><h2 className="mt-3 font-display text-xl text-[#F8F5EA]">Continúa con el estudio bíblico</h2><p className="mt-2 text-sm leading-relaxed text-[#C9C3B3]">Si deseas realizar el estudio, registra tu correo.</p><Link to={`/acceso?next=${encodeURIComponent(next)}`} className="mt-4 inline-flex min-h-11 items-center justify-center rounded-xl bg-[#D4AF37] px-5 text-sm font-bold text-black">Registrar mi correo</Link></aside>}

function SupportCard(){return <aside className="mt-4 rounded-[1.35rem] border border-[#D4AF37]/20 bg-[#0B0B0B] p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#D4AF37]/10 text-[#D4AF37]"><HandHeart className="h-5 w-5"/></span><div><h2 className="font-display text-lg text-[#F8F5EA]">Ayúdanos a sostener esta misión</h2><p className="mt-1 text-sm leading-relaxed text-[#C9C3B3]">Los estudios publicados permanecen disponibles gratuitamente. Tu aporte voluntario ayuda a preparar nuevos recursos de evangelización.</p><Link to="/donar" className="mt-3 inline-flex rounded-lg border border-[#D4AF37]/35 px-3 py-2 text-xs font-bold text-[#D4AF37]">Apoyar La Voz de Jesús</Link></div></div></aside>}

function Generating(){return <div className="rounded-[1.5rem] border border-[#D4AF37]/25 bg-[#0B0B0B] p-6 text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-[#D4AF37]"/><h2 className="mt-4 font-display text-xl">Estamos preparando tu estudio bíblico</h2><div className="mt-4 space-y-2 text-sm text-[#C9C3B3]">{["Reuniendo traducciones","Analizando estructura","Identificando palabras clave","Elaborando síntesis teológica","Preparando Lectio Divina"].map(x=><p key={x}>{x}</p>)}</div></div>}
function ComparisonPreview({columns,start,end}:{columns:PreviewColumn[];start:number;end:number}){const numbers=Array.from(new Set(columns.flatMap(column=>column.versiculos.filter(verse=>verse.versiculo>=start&&verse.versiculo<=end).map(verse=>verse.versiculo)))).sort((a,b)=>a-b);return <section className="mb-4 overflow-hidden rounded-[1.35rem] border border-[#D4AF37]/25 bg-[#0B0B0B]"><div className="border-b border-[#D4AF37]/20 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#D4AF37]">Comparación del pasaje</p><h2 className="mt-1 font-display text-xl text-[#F8F5EA]">Textos de las versiones bíblicas</h2></div><div className="overflow-x-auto"><div className="grid min-w-[36rem]" style={{gridTemplateColumns:`repeat(${columns.length}, minmax(12rem, 1fr))`}}>{columns.map(column=><div key={column.version.codigo} className="border-r border-[#D4AF37]/15 bg-[#111111] p-3 last:border-r-0"><strong className="block text-xs uppercase tracking-wider text-[#D4AF37]">{column.version.abreviatura}</strong><span className="mt-1 block text-[11px] text-[#C9C3B3]">{column.version.nombre} · Capítulo {column.capitulo}</span></div>)}{numbers.map(number=>columns.map(column=>{const verse=column.versiculos.find(item=>item.versiculo===number);return <article key={`${column.version.codigo}-${number}`} className="border-r border-t border-[#D4AF37]/10 p-3 last:border-r-0"><sup className="mr-1.5 font-bold text-[#D4AF37]">{number}</sup><span className="text-sm leading-relaxed text-[#F8F5EA]/90">{verse?.texto||"—"}</span></article>;}))}</div></div></section>}
function StudyView({study,tab,setTab}:{study:BibleStudy;tab:Tab;setTab:(t:Tab)=>void}){const d=study.contenido as Data;return <><section className="mb-3 rounded-2xl border border-[#D4AF37]/25 bg-[#0B0B0B] p-4"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-[#D4AF37]">{study.referencia}</p><h1 className="mt-1 font-display text-2xl">{study.titulo||d.titulo}</h1></div><button aria-label="Compartir" onClick={()=>navigator.share?.({title:study.titulo,text:study.referencia,url:location.href})}><Share2 className="text-[#D4AF37]"/></button></div>{!study.revisado&&<p className="mt-3 rounded-lg bg-[#D4AF37]/10 p-2 text-xs text-[#F2D27A]">Contenido pendiente de revisión editorial.</p>}</section><div className="mb-3 flex gap-1 overflow-x-auto rounded-xl border border-[#D4AF37]/20 bg-[#0B0B0B] p-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-lg px-3 py-2 text-xs ${tab===t?"bg-[#D4AF37] font-bold text-black":"text-[#C9C3B3]"}`}>{t}</button>)}</div><section className="rounded-[1.35rem] border border-[#D4AF37]/20 bg-[#0B0B0B] p-4">{tab==="Texto"&&<TextTab d={d}/>} {tab==="Comparación"&&<ComparisonTab d={d}/>} {tab==="Estructura"&&<StructureTab d={d}/>} {tab==="Teología"&&<TheologyTab d={d}/>} {tab==="Oración"&&<PrayerTab d={d}/>}</section></>}
const Block=({title,children}:{title:string;children:React.ReactNode})=><div className="mb-5 last:mb-0"><h2 className="mb-2 font-display text-lg text-[#D4AF37]">{title}</h2><div className="space-y-2 text-sm leading-relaxed text-[#F8F5EA]/90">{children}</div></div>;
const List=({items}:{items?:unknown[]})=><ul className="list-disc space-y-1 pl-5">{(items||[]).map((x,i)=><li key={i}>{typeof x==="string"?x:JSON.stringify(x)}</li>)}</ul>;
function TextTab({d}:{d:Data}){return <>{Object.entries(d.textos||{}).map(([k,v])=><Block key={k} title={k==="platense"?"Biblia Platense · Versión principal":k==="torres_amat"?"Torres Amat":"Scío de San Miguel"}><p>{v.disponible?v.texto:"Esta versión disponible no contiene el pasaje."}</p></Block>)}</>}
function ComparisonTab({d}:{d:Data}){const c=d.comparacion_traducciones||{};const version=(key:string)=>(c[key]||{}) as Comparison;return <><Block title="Comprensión global"><p>{d.comprension_global}</p></Block>{["platense","torres_amat","scio"].map(k=><Block key={k} title={k.replace("_"," ")}><p><b>Época:</b> {version(k).epoca}</p><p><b>Estilo:</b> {version(k).estilo}</p><List items={version(k).matices}/></Block>)}<Block title="Coincidencias"><List items={c.coincidencias as string[]}/></Block><Block title="Diferencias relevantes"><List items={c.diferencias_relevantes as string[]}/><p>{c.conclusion as string}</p></Block></>}
function StructureTab({d}:{d:Data}){return <><Block title="Delimitación"><p>{d.delimitacion?.unidad}</p><p>{d.delimitacion?.justificacion}</p></Block><Block title="Género literario"><p><b>{d.genero_literario?.tipo}</b></p><p>{d.genero_literario?.explicacion}</p></Block><Block title="Estructura"><List items={(d.estructura||[]).map(x=>`${x.versiculos}: ${x.titulo} — ${x.explicacion}`)}/></Block><Block title="Proposiciones"><List items={(d.proposiciones||[]).map(x=>`${x.tipo}: ${x.texto} — ${x.explicacion}`)}/></Block><Block title="Palabras clave"><List items={(d.palabras_clave||[]).map(x=>`${x.termino}: ${x.significado}. ${x.funcion_en_el_texto}`)}/></Block></>}
function TheologyTab({d}:{d:Data}){return <><Block title="Contexto histórico"><p>{d.contexto_historico}</p></Block><Block title="Contexto bíblico"><p>{d.contexto_biblico}</p></Block><Block title="Mensaje teológico"><p>{d.mensaje_teologico}</p></Block><Block title="Lectura cristológica"><p>{d.mensaje_cristologico}</p></Block><Block title="Referencias cruzadas"><List items={(d.referencias_cruzadas||[]).map(x=>`${x.referencia}: ${x.relacion}`)}/></Block><Block title="Actualización pastoral"><p>{d.actualizacion_pastoral}</p></Block></>}
function PrayerTab({d}:{d:Data}){return <><Block title="Aplicación espiritual"><p>{d.aplicacion_espiritual}</p></Block><Block title="Preguntas para meditar"><List items={d.preguntas_para_meditar}/></Block>{Object.entries(d.lectio_divina||{}).map(([k,v])=><Block key={k} title={k[0].toUpperCase()+k.slice(1)}><p>{String(v)}</p></Block>)}</>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block text-[10px] uppercase tracking-wider text-[#D4AF37]">{label}</span><span className="block [&_input]:h-11 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-[#D4AF37]/25 [&_input]:bg-[#111] [&_input]:px-3 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-[#D4AF37]/25 [&_select]:bg-[#111] [&_select]:px-3">{children}</span></label>}
