<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/biblia-ajuste-ester.php';require_login();$pdo=lvj_files_db();$message='';$error='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'');if($action==='aplicar'){$r=ester_apply($pdo);$message="Corrección aplicada: {$r['created']} versículos creados y {$r['moved']} relaciones reasignadas. Lote {$r['id']}.";log_activity('ajustar_ester_torresamat','lvj_bib_ester_ajustes',$r['id'],$message);}elseif($action==='revertir'){$id=(int)($_POST['id']??0);ester_revert($pdo,$id);$message="Ajuste $id revertido.";}else throw new RuntimeException('Acción no permitida.');}$audit=ester_audit($pdo);}catch(Throwable $e){$error=$e->getMessage();$audit=$audit??null;}
$pageTitle='Ajuste auxiliar de Ester';$pageSubtitle='TORRESAMAT 10:3 → capítulos 10–16';require __DIR__.'/includes/header.php';?>
<section class="page-heading"><div><span class="eyebrow">Herramienta auxiliar</span><h1>Corrección de Ester</h1><p>No modifica otras versiones, libros ni pantallas administrativas.</p></div></section><?php if($message):?><div class="alert success"><?php echo e($message);?></div><?php endif;?><?php if($error):?><div class="alert error"><?php echo e($error);?></div><?php endif;?>
<?php if($audit):?><section class="stats-grid"><article class="stat-card"><span>Referencias esperadas</span><strong>109</strong></article><article class="stat-card"><span>Detectadas</span><strong><?php echo $audit['detected'];?></strong></article><article class="stat-card"><span>Faltantes</span><strong><?php echo $audit['missing'];?></strong></article><article class="stat-card"><span>Colisiones</span><strong><?php echo $audit['collisions'];?></strong></article></section>
<section class="panel-card"><div class="alert error"><strong>Impacto:</strong> se modifica únicamente TORRESAMAT Ester 10:3, se crean 108 registros para 10:4–16:24, se cambia el libro de 10 a 16 capítulos y se reasignan 109 relaciones. Todo queda respaldado y es reversible.</div><?php if($audit['ready']):?><form method="post" onsubmit="return confirm('Se crearán 108 versículos, se reasignarán 109 relaciones y Ester TORRESAMAT pasará a 16 capítulos. Hay respaldo y reversión. ¿Continuar?');"><?php echo csrf_field();?><input type="hidden" name="action" value="aplicar"><button class="btn btn-gold" type="submit">Aplicar corrección completa de Ester</button></form><?php elseif($audit['active']):?><div class="alert success">La corrección ya está aplicada.</div><form method="post" onsubmit="return confirm('Se restaurará exactamente la estructura anterior de Ester. ¿Continuar?');"><?php echo csrf_field();?><input type="hidden" name="action" value="revertir"><input type="hidden" name="id" value="<?php echo (int)$audit['active'];?>"><button class="btn btn-soft" type="submit">Revertir corrección</button></form><?php else:?><div class="alert error">No se puede aplicar hasta obtener 109 referencias, cero faltantes y cero colisiones.</div><?php endif;?></section>
<section class="panel-card"><h2>Vista previa completa</h2><div class="table-wrap"><table><thead><tr><th>Referencia</th><th>Texto conservado</th></tr></thead><tbody><?php foreach($audit['preview'] as $row):?><tr><td><strong><?php echo e($row['key']);?></strong></td><td><?php echo e($row['text']);?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?><?php require __DIR__.'/includes/footer.php';?>
