<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/auth.php'; require_login();
$pdo=lvj_files_db(); $message=''; $error=''; $allowed=['generando','revision','publicado','error','archivado'];
$state=(string)($_GET['estado']??'revision'); if(!in_array($state,$allowed,true))$state='revision';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);$action=(string)($_POST['action']??'');try{if(!$id)throw new RuntimeException('Estudio no válido.');
  if($action==='aprobar'){$sql="UPDATE lvj_bib_estudios_ia SET estado='publicado',revisado=1,revisado_por=:admin,updated_at=NOW() WHERE id=:id AND deleted_at IS NULL";$params=['admin'=>(int)(current_user()['id']??0),'id'=>$id];}
  elseif($action==='publicar'){$sql='UPDATE lvj_bib_estudios_ia SET es_publico=1,updated_at=NOW() WHERE id=:id AND estado=\'publicado\' AND revisado=1 AND deleted_at IS NULL';$params=['id'=>$id];}
  elseif($action==='ocultar'){$sql='UPDATE lvj_bib_estudios_ia SET es_publico=0,updated_at=NOW() WHERE id=:id AND deleted_at IS NULL';$params=['id'=>$id];}
  elseif($action==='archivar'){$sql="UPDATE lvj_bib_estudios_ia SET estado='archivado',es_publico=0,updated_at=NOW() WHERE id=:id AND deleted_at IS NULL";$params=['id'=>$id];}
  elseif($action==='regenerar'){$sql="UPDATE lvj_bib_estudios_ia SET hash_contexto=SHA2(CONCAT(hash_contexto,'|archivado|',UTC_TIMESTAMP(6)),256),estado='archivado',es_publico=0,deleted_at=NOW(),updated_at=NOW() WHERE id=:id AND deleted_at IS NULL";$params=['id'=>$id];}
  else throw new RuntimeException('Acción no permitida.');$stmt=$pdo->prepare($sql);$stmt->execute($params);log_activity($action,'lvj_bib_estudios_ia',(int)$id,'Revisión editorial de estudio bíblico');$message=$action==='regenerar'?'El estudio fue archivado; la siguiente solicitud generará una versión nueva.':'Estudio actualizado.';
}catch(Throwable $e){$error=$e->getMessage();}}
$page=max(1,(int)($_GET['page']??1));$limit=20;$offset=($page-1)*$limit;$count=$pdo->prepare('SELECT COUNT(*) FROM lvj_bib_estudios_ia WHERE estado=:state AND deleted_at IS NULL');$count->execute(['state'=>$state]);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$limit));
$list=$pdo->prepare('SELECT e.id,e.referencia,e.titulo,e.nivel,e.estado,e.proveedor_ia,e.modelo_ia,e.revisado,e.es_publico,e.tokens_entrada,e.tokens_salida,e.costo_estimado,e.created_at,(SELECT COUNT(*) FROM lvj_bib_estudios_ia_solicitudes s WHERE s.estudio_id=e.id) solicitudes FROM lvj_bib_estudios_ia e WHERE e.estado=:state AND e.deleted_at IS NULL ORDER BY e.created_at DESC LIMIT :limit OFFSET :offset');$list->bindValue(':state',$state);$list->bindValue(':limit',$limit,PDO::PARAM_INT);$list->bindValue(':offset',$offset,PDO::PARAM_INT);$list->execute();$rows=$list->fetchAll();
$pageTitle='Estudios bíblicos';require __DIR__.'/includes/header.php';?>
<section class="page-heading"><div><span class="eyebrow">Biblia</span><h1>Estudios bíblicos</h1><p>Revisa, aprueba y publica los estudios preparados.</p></div></section>
<?php if($message):?><div class="alert success"><?php echo e($message);?></div><?php endif;?><?php if($error):?><div class="alert error"><?php echo e($error);?></div><?php endif;?>
<section class="content-toolbar"><div class="content-tabs"><?php foreach($allowed as $filter):?><a class="<?php echo $filter===$state?'active':'';?>" href="biblia-estudios-ia.php?estado=<?php echo e($filter);?>"><?php echo e(ucfirst($filter));?></a><?php endforeach;?></div></section>
<section class="panel-card"><div class="table-wrap"><table><thead><tr><th>Estudio</th><th>Nivel</th><th>Proveedor</th><th>Solicitudes</th><th>Revisión</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="7">No hay estudios en este estado.</td></tr><?php endif;?><?php foreach($rows as $row):?><tr><td><strong><?php echo e((string)($row['titulo']?:$row['referencia']));?></strong><br><span class="muted"><?php echo e((string)$row['referencia']);?></span></td><td><?php echo e(ucfirst((string)$row['nivel']));?></td><td><?php echo e((string)($row['proveedor_ia']?:'—'));?><br><small><?php echo e((string)($row['modelo_ia']?:''));?></small></td><td><?php echo (int)$row['solicitudes'];?></td><td><?php echo $row['revisado']?'Revisado':'Pendiente';?><br><?php echo $row['es_publico']?'Público':'Privado';?></td><td><?php echo e((string)$row['created_at']);?></td><td class="table-actions"><a class="action-button" href="biblia-estudio-ia.php?id=<?php echo (int)$row['id'];?>">Ver / editar</a><?php foreach(['aprobar'=>'Aprobar','publicar'=>'Publicar','ocultar'=>'Ocultar','regenerar'=>'Regenerar','archivar'=>'Archivar'] as $action=>$label):?><form method="post"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo (int)$row['id'];?>"><input type="hidden" name="action" value="<?php echo e($action);?>"><button class="action-button" type="submit"><?php echo e($label);?></button></form><?php endforeach;?></td></tr><?php endforeach;?></tbody></table></div><?php if($pages>1):?><div class="pagination"><?php for($n=1;$n<=$pages;$n++):?><a class="<?php echo $n===$page?'active':'';?>" href="?estado=<?php echo e($state);?>&amp;page=<?php echo $n;?>"><?php echo $n;?></a><?php endfor;?></div><?php endif;?></section><?php require __DIR__.'/includes/footer.php';?>
